#!/bin/sh

GREP="grep"

if [ $# -eq 0 -o "$1" = "-h" ] ; then
    echo "Usage: $0 pattern logfile1 [... logfileN]"
    exit 1
fi

pattern="$1"

if [ -z "$2" ] ; then
    logfiles='/var/log/maillog'
else
    shift
    logfiles="$@"
fi

ids=$($GREP -i "postfix/.*$pattern" "$logfiles" | awk '{print $6}' | sed 's/://')

test -z "$ids" && exit

for id in $ids
do
  if [ "$id" = "NOQUEUE" ]
  then
    $GREP " $id:.*$pattern" "$logfiles" && echo
  else
    $GREP " $id: " "$logfiles" && echo
  fi
done
